version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: bacchus_office_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: niyaz2004
      POSTGRES_DB: bacchus_office_db
    ports:
      - "5433:5432"
    volumes:
      - office_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bacchus_office_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bacchus_office_redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - office_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  office_pgdata:
  office_redisdata: