"""initial_office_ecosystem_baseline

Revision ID: 535a6aa5cbc8
Revises: 
Create Date: 2026-09-14 15:56:07.464787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535a6aa5cbc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('route_path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['office_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_actor_date', 'office_audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_office_audit_logs_actor_id'), 'office_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_office_audit_logs_created_at'), 'office_audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_office_audit_logs_created_at'), table_name='office_audit_logs')
    op.drop_index(op.f('ix_office_audit_logs_actor_id'), table_name='office_audit_logs')
    op.drop_index('idx_audit_logs_actor_date', table_name='office_audit_logs')
    op.drop_table('office_audit_logs')
    # ### end Alembic commands ###