"""add_call_dispositions_and_document_checkboxes

Revision ID: 77b9357af72d
Revises: 535a6aa5cbc8
Create Date: 2026-09-24 00:59:48.935509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b9357af72d'
down_revision: Union[str, None] = '535a6aa5cbc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_call_records', sa.Column('portfolio_sent', sa.Boolean(), nullable=False))
    op.add_column('office_call_records', sa.Column('proposal_sent', sa.Boolean(), nullable=False))
    op.add_column('office_leads', sa.Column('portfolio_sent', sa.Boolean(), nullable=False))
    op.add_column('office_leads', sa.Column('portfolio_sent_at', sa.DateTime(), nullable=True))
    op.add_column('office_leads', sa.Column('proposal_sent', sa.Boolean(), nullable=False))
    op.add_column('office_leads', sa.Column('proposal_sent_at', sa.DateTime(), nullable=True))
    op.add_column('office_leads', sa.Column('sla_deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office_leads', 'sla_deadline')
    op.drop_column('office_leads', 'proposal_sent_at')
    op.drop_column('office_leads', 'proposal_sent')
    op.drop_column('office_leads', 'portfolio_sent_at')
    op.drop_column('office_leads', 'portfolio_sent')
    op.drop_column('office_call_records', 'proposal_sent')
    op.drop_column('office_call_records', 'portfolio_sent')
    # ### end Alembic commands ###